"""Initial workforce schema: users, sessions, shifts, employees, face registrations,
cameras, assignments, footage imports, recognition events, jobs, audit log, settings.

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 17:40:53.500152
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('camera_type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=14), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_message', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("camera_type IN ('dome', 'bullet', 'turret', 'ptz', 'box', 'other')", name='ck_cameras_type'),
    sa.CheckConstraint("connection_status IN ('not_verified', 'online', 'offline')", name='ck_cameras_connection'),
    sa.CheckConstraint("direction IN ('entry', 'exit', 'entry_exit')", name='ck_cameras_direction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_cameras_code_ci', 'cameras', [sa.literal_column('lower(camera_code)')], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("shift_type IN ('morning', 'general', 'evening', 'night', 'custom')", name='ck_shifts_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_shifts_status'),
    sa.CheckConstraint('grace_period_minutes BETWEEN 0 AND 240', name='ck_shifts_grace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_shifts_name_ci', 'shifts', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('administrator', 'hr_manager', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_target', 'audit_log', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('face_status', sa.String(length=20), nullable=False),
    sa.Column('face_registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_registration_id', sa.UUID(), nullable=True),
    sa.Column('reregistration_requested', sa.Boolean(), nullable=False),
    sa.Column('reregistration_reason', sa.String(length=300), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IN ('full_time', 'part_time', 'contract', 'intern')", name='ck_employees_employment_type'),
    sa.CheckConstraint("face_status IN ('not_registered', 'processing', 'registered', 'failed')", name='ck_employees_face_status'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_employees_status'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_shift_id'), 'employees', ['shift_id'], unique=False)
    op.create_index('uq_employees_code_ci', 'employees', [sa.literal_column('lower(employee_code)')], unique=True)
    op.create_index('uq_employees_email_ci', 'employees', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('footage_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('capture_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('gallery_employee_count', sa.Integer(), nullable=True),
    sa.Column('identity_decisions', sa.Integer(), nullable=True),
    sa.Column('events_confirmed', sa.Integer(), nullable=True),
    sa.Column('events_needs_review', sa.Integer(), nullable=True),
    sa.Column('events_other', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed')", name='ck_footage_status'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footage_recordings_camera_id'), 'footage_recordings', ['camera_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_system_settings_singleton'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('employee_camera_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assignment_type IN ('entry', 'exit')", name='ck_assignments_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_assignments_status'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'camera_id', 'assignment_type', name='uq_assignment')
    )
    op.create_index(op.f('ix_employee_camera_assignments_camera_id'), 'employee_camera_assignments', ['camera_id'], unique=False)
    op.create_index(op.f('ix_employee_camera_assignments_employee_id'), 'employee_camera_assignments', ['employee_id'], unique=False)
    op.create_table('face_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('capture_method', sa.String(length=10), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_media_type', sa.String(length=40), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('failure_reason', sa.String(length=40), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('det_score', sa.Float(), nullable=True),
    sa.Column('face_size_px', sa.Integer(), nullable=True),
    sa.Column('head_pose', sa.String(length=10), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('model_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("capture_method IN ('upload', 'camera')", name='ck_face_registrations_capture'),
    sa.CheckConstraint("status IN ('processing', 'registered', 'failed', 'superseded', 'removed')", name='ck_face_registrations_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_registrations_employee_id'), 'face_registrations', ['employee_id'], unique=False)
    op.create_table('recognition_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_method', sa.String(length=30), nullable=True),
    sa.Column('identity_decision_id', sa.String(length=64), nullable=True),
    sa.Column('track_segment_id', sa.String(length=64), nullable=False),
    sa.Column('source_offset_ms', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('in', 'out')", name='ck_events_type'),
    sa.CheckConstraint("status IN ('confirmed', 'needs_review', 'rejected', 'duplicate', 'camera_not_assigned')", name='ck_events_status'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['footage_recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', 'track_segment_id', name='uq_events_segment')
    )
    op.create_index('ix_events_employee_time', 'recognition_events', ['employee_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_time', 'recognition_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_recognition_events_camera_id'), 'recognition_events', ['camera_id'], unique=False)
    # employees <-> face_registrations reference each other, so this key is added last.
    op.create_foreign_key('fk_employees_active_registration', 'employees', 'face_registrations',
                          ['active_registration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_active_registration', 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_recognition_events_camera_id'), table_name='recognition_events')
    op.drop_index('ix_events_time', table_name='recognition_events')
    op.drop_index('ix_events_employee_time', table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_index(op.f('ix_face_registrations_employee_id'), table_name='face_registrations')
    op.drop_table('face_registrations')
    op.drop_index(op.f('ix_employee_camera_assignments_employee_id'), table_name='employee_camera_assignments')
    op.drop_index(op.f('ix_employee_camera_assignments_camera_id'), table_name='employee_camera_assignments')
    op.drop_table('employee_camera_assignments')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_footage_recordings_camera_id'), table_name='footage_recordings')
    op.drop_table('footage_recordings')
    op.drop_index('uq_employees_email_ci', table_name='employees', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('uq_employees_code_ci', table_name='employees')
    op.drop_index(op.f('ix_employees_shift_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_audit_target', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('uq_shifts_name_ci', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_cameras_code_ci', table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
